language: node_js
node_js:
  - 0.10
before_install:
  - npm --version
  - npm config set spin false
  - phantomjs --version
script:
  - npm run ci
notifications:
  email:
    - build@ariatemplates.com
